### PR TITLE
Release

### PR DESCRIPTION
**Pull request by WinterCore**
On this branch, we have developed a heatmap of the Smashing Magazine. On the index.html file, we added all the structure of the page keeping the similarity with the original elements. On the style.ccs file we added the properties to position the items and style them according to the original page and applying a gray graduation color according to the hierarchy of the elements. Also, we have styled the text using Google fonts according to the theory learned in this project.

## Features and Elements:

- Added and position all the elements
- Set up the elements hide according to the screen size for the Navbar
- Set up the picture hover effect
- Styled text using Google Fonts
- Set up responsiveness for the position of the elements similar to the original site
- Set up gray graduation for the hierarchy of the elements

### CODE REVIEW

**Review by trekab — CHANGES_REQUESTED** [review]
# Changes Required!
Hi @WinterCore and @MarilenaRoque, great job so far! :clap: I like your detailed pull request description! :+1: There are some changes you need to make to this project to complete. These are;
### Mandatory:
- [ ] Your Live demo link does not lead to the latest version of your clone.
- [ ] Your CSS files are wrongly linked to your HTML making your clone appear without any styling. Please remove the starting `/` in the `href` attribute of your CSS linking tags.
- [ ] The footer should contain centered __links__.

### Optional:
- [ ] Check out [this plugin](https://chrome.google.com/webstore/detail/full-page-screen-capture/fdpohaocaechififmbbbbbknoalclacl?hl=en) which enables you to take full-page screenshots.

__Please make the necessary changes and submit another code review request!__
_Feel free to reach me on slack for any inquiries about this review._ :wink: 
__Treasure Kabareebe__
[GitHub](https://github.com/trekab) | [LinkedIn](https://www.linkedin.com/in/treasure-kabareebe/) | [Twitter](https://twitter.com/TKabareebe)

**Comment by WinterCore** [comment]
@trekab Thanks for your review.
The requested changes have been added.

> Your Live demo link does not lead to the latest version of your clone.

The live demo link is using Github pages and it's currently only enabled on the master branch. So as soon as we merge with the master branch the link will start working.

**Review by trekab — COMMENTED** [review]
Your welcome @WinterCore. :+1: Checkout [how to deploy on netlify](https://www.netlify.com/blog/2016/09/29/a-step-by-step-guide-deploying-on-netlify/). It is simple and convenient in that you can deploy any branch of your choice. :wink:

**Comment by rammazzoti2000** [comment]
## Project Approved :rocket: :tada: 
Hello team great job, your project is approved, feel free to merge whenever you are ready.
One more thing, your live demo still appears to be off, please updated it :smile: 
###
Cheers and Happy coding! :clap: 

##### Code review by Alexandru Bangau

(Feel free to contact me on slack by the handle of alexandru if you have any additional question)</em>
### :heavy_check_mark: Status: Approved

**Pull request merged**
